# Generated by Django 5.0.1 on 2024-01-25 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='applicant_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, null=True)),
                ('portfolio', models.ImageField(blank=True, null=True, upload_to='movies/applicant_portfolio')),
            ],
            options={
                'verbose_name': 'Соискатель',
                'verbose_name_plural': 'Соискатель',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employer_releted_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('inn', models.CharField(max_length=100)),
                ('title_org', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo_org', models.ImageField(blank=True, null=True, upload_to='movies/employer')),
                ('job_title', models.CharField(max_length=100)),
                ('status_validatio', models.CharField(max_length=100)),
                ('job_example', models.ImageField(blank=True, null=True, upload_to='movies/employer')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчик',
            },
        ),
    ]
