# Generated by Django 4.2.2 on 2024-02-14 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='applicant_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ImageField(blank=True, null=True, upload_to='movies/applicant_portfolio')),
            ],
            options={
                'verbose_name': 'Соискатель',
                'verbose_name_plural': 'Соискатель',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employer_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title_org', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('photo_org', models.ImageField(blank=True, null=True, upload_to='movies/employer')),
                ('inn', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status_valid', models.BooleanField(default=False, null=True)),
                ('job_example', models.ImageField(blank=True, null=True, upload_to='movies/employer')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчик',
            },
        ),
    ]
