# Generated by Django 4.2.2 on 2023-10-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Соискатель', 'verbose_name_plural': 'Соискатель'},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчик'},
        ),
        migrations.AlterField(
            model_name='applicant',
            name='portfolio',
            field=models.ImageField(blank=True, null=True, upload_to='movies/applicant_portfolio'),
        ),
    ]
