# Generated by Django 4.2.2 on 2024-01-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='job_title',
            new_name='status_valid',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='status_validatio',
        ),
    ]
