# Generated by Django 4.2.2 on 2024-04-14 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='job_example',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='portfolio',
        ),
        migrations.CreateModel(
            name='Employer_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_image', models.ImageField(blank=True, null=True, upload_to='employer/achievements', verbose_name='Фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_employer_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_image', models.ImageField(blank=True, null=True, upload_to='applicant/portfolio', verbose_name='Фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_applicant_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='achievements',
            field=models.ManyToManyField(blank=True, null=True, related_name='achievements', to='profiles.employer_image', verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='portfolio',
            field=models.ManyToManyField(blank=True, null=True, related_name='portfolio', to='profiles.applicant_image', verbose_name='Портфолио'),
        ),
    ]
