# Generated by Django 4.2.2 on 2023-10-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
