# Generated by Django 4.2.2 on 2024-03-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='job_example',
            field=models.ImageField(null=True, upload_to='movies/employer'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='photo_org',
            field=models.ImageField(null=True, upload_to='movies/employer'),
        ),
    ]
