# Generated by Django 4.2.2 on 2024-03-31 17:16

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_applicant_resume_count_employer_vacancy_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='portfolio',
            field=models.ImageField(blank=True, null=True, upload_to='movies/applicant_portfolio', verbose_name='Портфолио'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='response',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None, verbose_name='Отклики'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume_count',
            field=models.IntegerField(default=0, verbose_name='Счетчик резюме'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='applicant_user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='job_example',
            field=models.ImageField(blank=True, null=True, upload_to='employer', verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='photo_org',
            field=models.ImageField(blank=True, null=True, upload_to='employer', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='status_valid',
            field=models.BooleanField(default=False, null=True, verbose_name='Статус проверки ИНН'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='title_org',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employer_user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='vacancy_count',
            field=models.IntegerField(default=0, verbose_name='Счетчик вакансий'),
        ),
    ]
