# Generated by Django 4.2.2 on 2023-10-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_employer_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='male',
        ),
        migrations.AddField(
            model_name='applicant',
            name='sex',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], default=''),
        ),
    ]
