# Generated by Django 4.2.2 on 2024-01-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_job_title_employer_status_valid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='description',
        ),
        migrations.AlterField(
            model_name='employer',
            name='inn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='status_valid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='title_org',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
