# Generated by Django 4.2.2 on 2024-01-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_employer_inn_alter_employer_title_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='status_valid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='title_org',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
