# Generated by Django 4.2.2 on 2023-10-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_applicant_male_applicant_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='bio',
            new_name='about_us',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='male',
        ),
        migrations.AddField(
            model_name='employer',
            name='inn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='sex',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], default=''),
        ),
    ]
