# Generated by Django 5.0.1 on 2024-01-25 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(default='', max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('result', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Событие',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('tasks', models.CharField(blank=True, default='')),
                ('requirements', models.CharField(blank=True, default='')),
                ('salary_min', models.CharField(blank=True, default='', max_length=100)),
                ('salary_max', models.CharField(blank=True, default='', max_length=100)),
                ('tax', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='movies/vacancies')),
                ('required_experience', models.CharField(blank=True, default='', max_length=100)),
                ('graph', models.CharField(blank=True, default='', max_length=100)),
                ('comments_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансия',
            },
        ),
    ]
