# Generated by Django 5.0.1 on 2024-01-30 17:04

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(default='', max_length=100, null=True)),
                ('date_start', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_end', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(default='', max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_event', to='profiles.employer')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Событие',
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(default='', max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('tasks', models.CharField(blank=True, default='', null=True)),
                ('requirements', models.CharField(blank=True, default='', null=True)),
                ('salary_min', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('salary_max', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tax', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='movies/vacancies')),
                ('required_experience', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('graph', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('favorites_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_vacancy', to='profiles.employer')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансия',
            },
        ),
    ]
