# Generated by Django 4.2.2 on 2024-01-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='requirements',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='tasks',
            field=models.CharField(blank=True, default=''),
        ),
    ]
