# Generated by Django 4.2.2 on 2024-01-02 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='employer_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.employer'),
        ),
    ]
