# Generated by Django 4.2.2 on 2024-02-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_type_vacancies_employ_vacancies_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='salary_max',
            field=models.BigIntegerField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_min',
            field=models.BigIntegerField(blank=True, default='', max_length=100, null=True),
        ),
    ]
