# Generated by Django 4.2.2 on 2023-11-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_vacancies_employer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'Событие'},
        ),
        migrations.AlterModelOptions(
            name='vacancies',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансия'},
        ),
    ]
