# Generated by Django 4.2.2 on 2024-01-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='employer_id',
        ),
    ]
