# Generated by Django 4.2.2 on 2024-03-31 17:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_applicant_portfolio_alter_applicant_response_and_more'),
        ('jobs', '0002_alter_vacancies_employ'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='region',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='response',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_event', to='profiles.applicant', verbose_name='Откликнувшийся'),
        ),
        migrations.AlterField(
            model_name='response',
            name='data_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='response',
            name='date_start',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='response',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_event', to='profiles.employer', verbose_name='Работодатель'),
        ),
        migrations.AlterField(
            model_name='response',
            name='result',
            field=models.CharField(choices=[('Response', 'new_response'), ('Invite', 'invite'), ('Accepted', 'accepted_response'), ('Rejected', 'rejected_response')], default='new_vacancy_response', max_length=50, verbose_name='Тип отклика'),
        ),
        migrations.AlterField(
            model_name='response',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.vacancies', verbose_name='Вакансия'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_vacancy', to='profiles.employer', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='employ',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='graph',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='График'), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='job_title',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='movies/vacancies', verbose_name='Прелоадер'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='required_experience',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Требуемый опыт'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='requirements',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_max',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Максимальная зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_min',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Минемальная зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='tasks',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Задачи'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='tax',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Статус налога'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='timestamp',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
