# Generated by Django 4.2.2 on 2024-01-30 14:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_vacancies_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='result',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='graph',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='job_title',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='required_experience',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='requirements',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_max',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_min',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='tasks',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='tax',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
