# Generated by Django 4.2.2 on 2024-03-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_vacancies_citizenship_vacancies_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='com_logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото компании'),
        ),
    ]
