# Generated by Django 4.2.2 on 2024-01-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_vacancies_employer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='required_experience',
            field=models.CharField(blank=True, choices=[('nothing', 'Без опыта'), ('1to3', 'от 1 года до 3 лет'), ('3to6', 'от 3 до 6 лут'), ('6up', 'Более 6 лет')], default=''),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='requirements',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_max',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_min',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='tax',
            field=models.CharField(blank=True, choices=[('before', 'До вычета налогов'), ('after', 'На руки')], default=''),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='type',
            field=models.CharField(blank=True, choices=[('full', 'Полная'), ('partial', 'Частичная'), ('internship', 'Стажировка'), ('volunteering', 'Волонтерство')], default=''),
        ),
    ]
