# Generated by Django 4.2.2 on 2024-01-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_vacancies_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='required_experience',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='tax',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='type',
            field=models.CharField(blank=True, default=''),
        ),
    ]
