# Generated by Django 4.2.2 on 2024-01-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_vacancies_required_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='requirements',
            new_name='graph',
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='job_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='required_experience',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='tax',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
