# Generated by Django 4.2.2 on 2024-01-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_rename_requirements_vacancies_graph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
