# Generated by Django 4.2.2 on 2024-01-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_vacancies_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
