# Generated by Django 4.2.2 on 2024-01-10 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_vacancies_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='time',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 10, 18, 34, 26, 433934), null=True),
        ),
    ]
