<<<<<<< HEAD
# Generated by Django 4.2.2 on 2024-01-13 13:57
=======
# Generated by Django 4.2.2 on 2024-01-10 15:40
>>>>>>> 548067ffb084be1d6889e941b1bc29acb4f3b8f4

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_vacancies_time_vacancies_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='timestamp',
<<<<<<< HEAD
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 13, 16, 57, 12, 766936), null=True),
=======
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 10, 18, 40, 24, 737257), null=True),
>>>>>>> 548067ffb084be1d6889e941b1bc29acb4f3b8f4
        ),
    ]
