# Generated by Django 4.2.2 on 2024-01-10 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_vacancies_time_vacancies_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 10, 18, 40, 24, 737257), null=True),
        ),
    ]
