# Generated by Django 4.2.2 on 2024-01-12 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_vacancies_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 12, 18, 52, 7, 79885), null=True),
        ),
    ]
