# Generated by Django 4.2.2 on 2024-01-12 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_vacancies_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 13, 2, 18, 42, 495891), null=True),
        ),
    ]
