# Generated by Django 4.2.2 on 2024-01-13 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_vacancies_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 13, 15, 13, 7, 120853), null=True),
        ),
    ]
