# Generated by Django 4.2.2 on 2024-01-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_vacancies_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='timestamp',
        ),
    ]
