# Generated by Django 4.2.2 on 2023-10-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_title', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[('full', 'Полная'), ('partial', 'Частичная'), ('internship', 'Стажировка'), ('volunteering', 'Волонтерство')], default='')),
                ('about_us', models.TextField(default='', max_length=55)),
                ('experience', models.CharField(choices=[('nothing', 'Без опыта'), ('1to3', 'от 1 года до 3 лет'), ('3to6', 'от 3 до 6 лут'), ('6up', 'Более 6 лет')], default='')),
                ('skills', models.CharField(default='', max_length=100)),
                ('quality', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
