# Generated by Django 5.0.1 on 2024-01-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_title', models.CharField(default='', max_length=100)),
                ('type', models.CharField(blank=True, default='')),
                ('skills', models.CharField(blank=True, default='', max_length=100)),
                ('quality', models.CharField(blank=True, default='', max_length=100)),
                ('experience', models.CharField(blank=True, default='')),
                ('about_us', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('tm', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
