# Generated by Django 4.2.2 on 2023-10-21 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_applicant_options_alter_employer_options_and_more'),
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='applicant_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.applicant'),
        ),
    ]
