# Generated by Django 4.2.2 on 2024-01-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='applicant_id',
        ),
    ]
