# Generated by Django 4.2.2 on 2024-01-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_remove_summary_applicant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='summary',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='summary',
            name='tm',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='summary',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='about_us',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='summary',
            name='experience',
            field=models.CharField(blank=True, choices=[('nothing', 'Без опыта'), ('1to3', 'от 1 года до 3 лет'), ('3to6', 'от 3 до 6 лут'), ('6up', 'Более 6 лет')], default=''),
        ),
        migrations.AlterField(
            model_name='summary',
            name='quality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='type',
            field=models.CharField(blank=True, choices=[('full', 'Полная'), ('partial', 'Частичная'), ('internship', 'Стажировка'), ('volunteering', 'Волонтерство')], default=''),
        ),
    ]
