# Generated by Django 4.2.2 on 2024-01-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_summary_email_summary_phone_number_summary_tm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='experience',
            field=models.CharField(blank=True, choices=[('noExp', 'Без опыта'), ('1-3', 'от 1 года до 3 лет'), ('3-6', 'от 3 до 6 лут')], default=''),
        ),
        migrations.AlterField(
            model_name='summary',
            name='type',
            field=models.CharField(blank=True, default=''),
        ),
    ]
