# Generated by Django 4.2.2 on 2024-04-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'ноты'},
        ),
    ]
