# Generated by Django 4.2.2 on 2024-04-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('new_vacancy_response', 'new_vacancy_response'), ('accepted_vacancy_response', 'accepted_vacancy_response'), ('rejected_vacancy_response', 'rejected_vacancy_response'), ('vacancy_favorites', 'vacancy_favorites'), ('resume_favorites', 'resume_favorites')], max_length=50),
        ),
    ]
