# Generated by Django 5.0.1 on 2024-01-30 17:04

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('usertype', models.CharField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='movies/avatars')),
                ('vacancy_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('surname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, default='0001-01-01', null=True)),
                ('citizenship', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('region', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('about', models.CharField(blank=True, default='', null=True)),
                ('about_work', models.CharField(blank=True, default='', null=True)),
                ('telegram', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('website', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('recommendations', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователь',
            },
        ),
    ]
