# Generated by Django 4.2.2 on 2024-01-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aboutWork',
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='about_work',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
