# Generated by Django 4.2.2 on 2024-04-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Страна'),
        ),
    ]
