# Generated by Django 4.2.2 on 2024-03-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_recommendations_remove_user_resume_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, default='', null=True, verbose_name='О вас'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about_work',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Портфолио'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(blank=True, default='', help_text='Пример: 1999-10-12', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(help_text='Пример: employer/applicant', verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Сайт'),
        ),
    ]
