# Generated by Django 4.2.2 on 2023-09-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='movies/')),
                ('title', models.CharField(max_length=100)),
                ('salary_min', models.PositiveSmallIntegerField(default=0)),
                ('salary_max', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
    ]
