# Generated by Django 4.2.2 on 2023-09-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.CharField(default='ООО', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(default='Без опыта', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='place',
            field=models.CharField(default='Волгоград', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='require',
            field=models.CharField(default='Знания JS', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tasks',
            field=models.CharField(default='Работать', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='type',
            field=models.CharField(default='Частичная занятость', max_length=100),
        ),
    ]
