# Generated by Django 4.2.2 on 2023-09-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_vacancy_company_vacancy_experience_vacancy_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='tasks',
            field=models.CharField(max_length=100),
        ),
    ]
