# Generated by Django 5.0.3 on 2024-04-09 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_start', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('data_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('result', models.CharField(choices=[('Response', 'new_response'), ('Accepted', 'accepted_response'), ('Rejected', 'rejected_response')], default='new_vacancy_response', max_length=50, verbose_name='Тип отклика')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_event', to='profiles.applicant', verbose_name='Откликнувшийся')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_event', to='profiles.employer', verbose_name='Работодатель')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.vacancies', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклики',
                'verbose_name_plural': 'Отклики',
            },
        ),
    ]
