# Generated by Django 4.2.2 on 2023-09-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
