# Generated by Django 4.2.2 on 2023-09-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_alter_applicant_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='short_name',
            field=models.CharField(default='Сергеевич', max_length=100),
        ),
    ]
