# Generated by Django 4.2.2 on 2023-09-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_applicant_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='short_name',
            field=models.CharField(max_length=100),
        ),
    ]
