# Generated by Django 4.2.2 on 2024-04-13 14:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_title', models.CharField(default='', max_length=100, null=True, verbose_name='Название')),
                ('salary', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Зарплата')),
                ('employ', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None, verbose_name='Тип занятости')),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Навыки'), blank=True, default=list, null=True, size=None, verbose_name='Навыки')),
                ('quality', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None, verbose_name='Качества')),
                ('experience', models.CharField(blank=True, default='', null=True, verbose_name='Опыт')),
                ('about_us', models.TextField(blank=True, default='', null=True, verbose_name='О вам')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateField(auto_now=True, verbose_name='Дата вызова')),
                ('avatar', models.CharField(blank=True, null=True, verbose_name='Аватар')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Фамилия')),
                ('surname', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Отчество')),
                ('telegram', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Телеграм')),
                ('website', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Сайт')),
                ('phone_number', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Номер телефона')),
                ('date_of_birth', models.CharField(blank=True, default='', help_text='Пример: 1999-10-12', null=True, verbose_name='Дата рождения')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_resume', to='profiles.applicant', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
