# Generated by Django 4.2.2 on 2024-02-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
