# Generated by Django 4.2.2 on 2024-04-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about_us',
            field=models.TextField(blank=True, default='', null=True, verbose_name='О ваc'),
        ),
    ]
