# Generated by Django 4.2.2 on 2024-04-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Фото профиля'),
        ),
        migrations.AddField(
            model_name='resume',
            name='date_of_birth',
            field=models.CharField(blank=True, default='', help_text='Пример: 1999-10-12', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='resume',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='resume',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='resume',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Телеграм'),
        ),
        migrations.AddField(
            model_name='resume',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Сайт'),
        ),
    ]
