# Generated by Django 4.2.2 on 2024-03-09 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_vacancies_employ'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='vacancy',
            field=models.ManyToManyField(related_name='vacancies', to='jobs.vacancies'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
