# Generated by Django 4.2.2 on 2024-04-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_avatar_resume_date_of_birth_resume_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='avatar',
            field=models.CharField(blank=True, null=True, verbose_name='Аватар'),
        ),
    ]
