# Generated by Django 4.2.2 on 2024-03-31 17:16

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_applicant_portfolio_alter_applicant_response_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_vacancies_citizenship_vacancies_first_name_and_more'),
        ('resume', '0002_favorites_vacancy_alter_favorites_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='vacancy',
            field=models.ManyToManyField(related_name='vacancies', to='jobs.vacancies', verbose_name='Вакансия'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='about_us',
            field=models.TextField(blank=True, default='', null=True, verbose_name='О вам'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_resume', to='profiles.applicant', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='employ',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='quality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None, verbose_name='Качества'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_title',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Навыки'), blank=True, default=list, null=True, size=None, verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='timestamp',
            field=models.DateField(auto_now=True, verbose_name='Дата вызова'),
        ),
    ]
