# Generated by Django 4.2.2 on 2023-11-20 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DampUser',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(default='', upload_to='')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('surname', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(choices=[('Мужской', 0), ('Женский', 1)], default='')),
                ('birthday', models.DateField(default='2009-02-11')),
                ('citizenship', models.CharField(default='', max_length=20)),
                ('region', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
