# Generated by Django 4.2.2 on 2023-12-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dampuser',
            name='gender',
            field=models.CharField(choices=[('Женский', 1), ('Мужской', 0)], default=''),
        ),
    ]
