# Generated by Django 4.2.2 on 2023-12-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damp', '0002_alter_dampuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dampuser',
            name='gender',
            field=models.CharField(choices=[('Мужской', 0), ('Женский', 1)], default=''),
        ),
    ]
