# Generated by Django 4.2.2 on 2024-01-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damp', '0003_alter_dampuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dampuser',
            name='birthday',
            field=models.DateField(default='1999-01-01'),
        ),
        migrations.AlterField(
            model_name='dampuser',
            name='gender',
            field=models.CharField(choices=[('Женский', 1), ('Мужской', 0)], default=''),
        ),
    ]
